### ISSUE TITLE
URL redirect issues when using ilifu SSO

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-node-server#153]
With the new ilifu SSO service, a URL that contains a link like `https://carta-beta.idia.ac.za/?file=/blah/myfile.fits` is not redirected properly after the user is redirected to the login page. The behaviour seems variable, where it sometimes continues to prompt me to log in (but does nothing when I click to "sign in"), until I edit the URL to remove the `/?file=...`, or at other times shows me the CARTA dashboard, and I have to press the back button to get back to the URL with the path in it (and pressing the forwards button will cause issues after that). 

I have not tested it, but presumably the same occurs with `/?folder=/blah` and `/?workspace=myworkspace` in the URL. 

The main issue is that I cannot launch CARTA with a filename (or similar) in the a URL and it do what I want. Since this is a CARTA feature, it would be good to add support back in for this.

**Comment by daikema** [comment]
>The behaviour seems variable, where it sometimes continues to prompt me to log in (but does nothing when I click to "sign in"), until I edit the URL to remove the /?file=..., or at other times shows me the CARTA dashboard

Have you noticed any patterns that might cause this specific difference in behaviour?  e.g. a particular browser and/or OS has this problem whereas others don't?  (Can you sent me any browser javascript console output that might be visible in this case to aid in debugging? DM me if you're not sure how to grab that)

**Comment by Jordatious** [comment]
If you try this URL, you may be able to reproduce the issue

https://carta-beta.idia.ac.za/frontend/?file=/carta_share/public/jcollier/THINGS/NGC_3198_NA_CUBE_THINGS.FITS

No I haven't noticed any pattern. I've only been using Chrome. I tried it again just now with that link and was redirected to the CARTA dashboard (see attached) with [this URL](https://carta-beta.idia.ac.za/dashboard?oidcuser=jcollier).

When I press back once I get [this URL](https://carta-beta.idia.ac.za/dashboard?err=Missing+OIDC+verifier) and an associated error pop up, and when I press back again it gives me [this URL](https://carta-beta.idia.ac.za/dashboard?redirectParams=P2ZpbGU9L2NhcnRhX3NoYXJlL3B1YmxpYy9qY29sbGllci9USElOR1MvTkdDXzMxOThfTkFfQ1VCRV9USElOR1MuRklUUw==). Trying the link again after all of this works.

I do see this in the console, but not sure if it's related...

```
dom.js:1     Failed to load resource: net::ERR_FILE_NOT_FOUND
dashboard.js:391 SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

<img width="1006" alt="image" src="https://github.com/CARTAvis/carta-controller/assets/10542136/a60ee4f2-72d9-4522-8e07-d0f4a9c6e8b2">
