### ISSUE TITLE
Cannot GET /carta

### ISSUE THREAD

**Issue by toddpfaff** [CARTAvis/carta-node-server#30]
After solving issue #28, I now have a CARTA Server 1.4 running.  Unfortunately, when I visit the CARTA server url, all that is
displayed in my browser is "Cannot GET /carta".  Nothing helpful shows up in my shell that is running the carta-node-server process - this is all I see in that window:
```
[carta@redacted tmp]$ carta-node-server
Checking config file /etc/carta/config.json
Serving CARTA frontend from /home/carta/node_modules/carta-frontend
Connected to server mongodb://localhost:27017 and database CARTA
Server initialised successfully at https://redacted.redact.ed/carta
Started listening for login requests on port 8000
LDAP connected correctly
```
Also, nothing is logged under /var/log/carta/:
```
[carta@redacted ~]# ls -al /var/log/carta/
total 1
drwxrwxr-x 2 carta carta 2 Nov  4 20:02 ./
drwxrwxr-x 3 carta carta 3 Nov  4 20:02 ../
```
Any suggestions as to how to begin diagnosing this?

**Comment by veggiesaurus** [comment]
This looks like a proxy issue. Are you using nginx?

**Comment by veggiesaurus** [comment]
@toddpfaff can I close this?

**Comment by toddpfaff** [comment]
I've been testing both via this reverse-proxy url path and directly via port 8000 behind the proxy.

Before [this](https://github.com/CARTAvis/carta-node-server/issues/28#issuecomment-729684465), neither direct or proxied were working.  After, direct is now working.  Will work on the reverse-proxy issue later, once I've got all kinks worked out with the direct path.

Yes, @veggiesaurus, we can close this issue now.  I'll do it with this comment.
