### ISSUE TITLE
Make carta-node-server (carta-controller?) installable through apt with all dependencies.

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-node-server#33]
Aims:

* A single PPA with all CARTA components and dependencies packaged.
* This should probably be a pre-built version which does not depend on an npm install -- needs further investigation. Installing through npm should remain as a separate option.

This should be part of an epic, together with the corresponding issues in other components.

**Comment by veggiesaurus** [comment]
note that `carta-node-server` requires NodeJS (which bundles NPM). There are plenty of ways to reliably install nodejs on ubuntu already, so we shouldn't bundle that. I propose that we only officially support the LTS releases of nodeJS as well

**Comment by confluence** [comment]
I'm putting this on hold indefinitely; this is available as an npm package, and I think installing it through npm is user-friendly enough.

**Comment by confluence** [comment]
I'm closing this because it's unlikely that it will be necessary.
