### ISSUE TITLE
Allow users to access the latest backend log via the dashboard

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-node-server#36]
Users should be able to access their current backend process' log via the dashboard. 

- [x] Keep an in-memory copy of output in a map (key: username, value: output as linked list)
- [x] Ensure the output is kept to a particular size limit
- [x] API endpoint: `GET` `/log`
- [x] Dashboard: Display log on demand (update when refresh button is pressed)

**Comment by veggiesaurus** [comment]
Issue is almost done. Just needs some testing and perhaps some CSS neatening by @charlcater

https://user-images.githubusercontent.com/592504/107248482-02f29880-6a3b-11eb-9a9a-188bbc653b3e.mp4

@kswang1029 does this look ok?

**Comment by kswang1029** [comment]
Is that with a semi-transparent background? I suggest we avoid that or apply Gaussian blur to the background layer to enhance the contrast of the text hence readability.

**Comment by veggiesaurus** [comment]
> Is that with a semi-transparent background? I suggest we avoid that or apply Gaussian blur to the background layer to enhance the contrast of the text hence readability.

Done:

![image](https://user-images.githubusercontent.com/592504/107322781-cb710400-6aad-11eb-970b-efb49fc24988.png)

**Comment by kswang1029** [comment]
neat!
