### ISSUE TITLE
Update Focal instructions

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-node-server#51]
* Install the backend with dependencies from a PPA, not from source
* Provide complete and comprehensive step-by-step instructions for a specific reference configuration
* Maybe move this section up and call it "Quick Start", to make the docs more user-friendly

**Comment by veggiesaurus** [comment]
@confluence this is in review/qa. Can we close it?

**Comment by confluence** [comment]
Yes; everything mentioned here is done and has been deployed.
